### ISSUE TITLE
Device-ID problem

### ISSUE THREAD

**Issue by jochenv** [PfisterDaniel/node-red-contrib-apple-find-me#14]
perhaps I am too dumb to enter it correctly, but I always get an error 500 when I enter the device id and want to send a message. message payload is empty in the debug node. thx:-)

**Comment by PfisterDaniel** [comment]
![2021-04-26 12_51_27-node-red-0 - ioBroker](https://user-images.githubusercontent.com/9358627/116072035-e4da2300-a68e-11eb-89d8-4190bfc3aef7.png)

I hope that help you by your configuration...

**Comment by PfisterDaniel** [comment]
Your Device-ID is a cryptical number

**Comment by jochenv** [comment]
thanks for the quick response. I did exactly the same, only with a different outcome
![Bildschirmfoto 2021-04-26 um 14 13 18](https://user-images.githubusercontent.com/11509948/116080679-a9912180-a699-11eb-9bb1-819927e7f537.png)

**Comment by jochenv** [comment]
![Bildschirmfoto 2021-04-26 um 14 15](https://user-images.githubusercontent.com/11509948/116081029-08ef3180-a69a-11eb-817d-f28c8005e3d8.jpg)

**Comment by PfisterDaniel** [comment]
Ok that's crazy, just isn't it working with the Apple Watch, or is it not working with any of your devices? I don't have an Apple Watch and I can't test it ...

**Comment by jochenv** [comment]
same result with my MacBook :(

**Comment by PfisterDaniel** [comment]
hmm ok, do you use the ID with or without quotation marks? Without its correct... 
Then I have no solution to the problem. Sorry ... could you take screenshots of all node settings again?

**Comment by jochenv** [comment]
![Bildschirmfoto 2021-04-26 um 15 02](https://user-images.githubusercontent.com/11509948/116087226-f298a400-a6a0-11eb-9581-1dde22d65bc8.jpg)
finding devices works fine, so the iTunes account settings seem to be ok

**Comment by jochenv** [comment]
oh, without quotation marks:-)

**Comment by PfisterDaniel** [comment]
Ok :-D does that mean it works?

**Comment by jochenv** [comment]
unfortunately not. just wanted to answer your previous question:-) all devices are found but I can't send a message to any, no matter what kind of device it is

**Comment by PfisterDaniel** [comment]
Ok, than go to the next test... Working messages from the Icloud Website?

**Comment by PfisterDaniel** [comment]
I have tested my own settings again, I only get this errors if the ID does not match. Do you have single quotes in your ID?

**Comment by PfisterDaniel** [comment]
or other special characters in your id. In my ID's there are only characters (a-zA-Z) and numbers (0-9) and /, +, =

**Comment by PfisterDaniel** [comment]
ok, then unfortunately I'm at a loss. Maybe someone else reading this can help. Another thing you could test would be an account of a friend or from a family member.

**Comment by jochenv** [comment]
yes, i’ll try that. thanks anyway for trying - and of course for the node itself, it’s really useful!

**Comment by PfisterDaniel** [comment]
You're welcome. I hope that the problem can still be solved with you

**Comment by jochenv** [comment]
i‘ll let you know if/when i manage to get it going:-)

**Comment by RaoulSargent** [comment]
_Before I comment - I totally agree, a fantastic "node-red" implementation, really appreciated._

I have the exact same problem as described.
Sending a message always fails with '500' 'Sending failed - check your device ID'

Summary:
"Find My Phone" Works
"Locate My Devices (Input)" Works (33 devices found)
"Send Message" Error 500 - "Sending failed - check your device ID"  [iMac, iPhoneXS, etc]

I will be happy to help diagnose.

**Comment by RaoulSargent** [comment]
I can confirm that using a different Apple account results in the same error.

I have an Apple "Family" of 5 people.
Using the "owner" of the device as the 'Account' within the "Send Message" node => fails error 500
Using a member of the "family" as the 'Account' within the "Send Message" node => fails error 500

Both accounts mentioned work fine for the other "Find/Locate" nodes, and retrieve data for all devices known to the "Family".

**Comment by PfisterDaniel** [comment]
> i‘ll let you know if/when i manage to get it going:-)
> […](#)
> Am 26.04.2021 um 18:22 schrieb Daniel Pfister ***@***.***>: ﻿ You're welcome. I hope that the problem can still be solved with you — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hello jochenv, please check if the Problem can be solvend with follow solution from RaoulSargent:
https://github.com/PfisterDaniel/node-red-contrib-apple-find-me/issues/15#issuecomment-840477868

br Daniel

**Comment by RaoulSargent** [comment]
Hope this helps... Things I have recently found/learnt:
- The "Device ID" can change, perhaps following iOS upgrades.  So need to include in your flow a check for the latest Device ID for a particular device; otherwise what was previously working and start to fail because the Device ID has changed
- Each Apple ID Account only has access to it's own devices
- With v1.1.0 (and suspected changes made by Apple) same "Family" devices now cannot be accessed either

This means that if I create a flow and use 'MY' Apple ID Account, that flow can only find/msg devices belonging to 'MY' Apple ID account.  It is a 1:1 relationship between Apple ID accounts and Devices.

In other words if the flow uses 'MY' Apple ID account and the flow wants to send a msg to my 'WIFE' iPhone then it will fail.
To achieve this I need to have a switch in the flow to use a different 'find-my' node to send the message, with that 'find-my' node using the Apple ID account of my 'WIFE'.

Previously I was using a "FAMILY" Apple ID in the flow for all actions to devices that belong to that same "FAMILY" - This does not work.  The 1:1 relationship is enforced.

As describe in Issue 15, I deleted my previously working flow and recreated it, and in doing so I discovered the change in Device ID and the 1:1 relationship.  So I suppose the moral of this story is that just because it was previously working before, consider that multiple things have now changed and you should review the whole flow.

Hope this helps.

**Comment by PfisterDaniel** [comment]
Hi, thank you for that detailed description. I couldn't have described it any better.
