### ISSUE TITLE
Timestamp timezone in CET - Could be changed to UTC

### ISSUE THREAD

**Issue by DaveDaveDaveDave** [PfisterDaniel/node-red-contrib-apple-find-me#9]
Hello,

Fantastic project!  Thanks!

A fairly minor thing, but would it be possible to standardize the timestamps as UTC vs Central Europe?

Is there a reason that times are currently reported in CET?

Thanks,
Dave

**Comment by PfisterDaniel** [comment]
Hello, Dave,

The reason is: Im living in Germany :-) That‘s all...

But you have Right, its a good idea... I'll take it into account in the next update. Thank you for the Feedback.

Br
Daniel

Am 14.03.2021 um 19:15 schrieb Bort ***@***.***>:


Hello,

Fantastic project! Thanks!

A fairly minor thing, but would it be possible to standardize the timestamps as UTC vs Central Europe?

Is there a reason that times are currently reported in CET?

Thanks,
Dave

**Comment by PfisterDaniel** [comment]
Hello Dave,

im published a new version that includes Timezone and Timeformats.
I hope thats solves your problem.

Br Daniel
